title: "Hack The Blog"
author: "Henry"
email: "hjw.cyber@gmail.com"
description: "Covering whatever interests me, with a focus on red-teaming." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / social media user names used by the site theme:
# All of these are optional and can be removed or commented out
github_username: "Henryisnotavailable"
linkedin_username: "henry-williams-175a23214"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: luxedo/jekyll-theme-potato-hacker
theme_base: "dark"
theme_switch: "on"

blog: on
avatar: on
avatar_image: "assets/img/avatar.jpg?raw=true"
avatar_description: "My inner thoughts"

highlighter_theme: gruvbox
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - dropdown2
  - About
  - dropdown1

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true

rss: rss
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  
titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
